{{- if .Values.operator }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ .Values.operator.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      control-plane: {{ .Values.operator.name }}
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: {{ .Values.operator.name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: vardir
          hostPath:
            path: /var
            type: Directory
        - name: rundir
          hostPath:
            path: /run
            type: Directory
        {{- if .Values.operator.isDind }}
        - name: containerdsock
          hostPath:
            path: /run/k3s/containerd
            type: Directory
        {{- end }}
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
            - --zap-log-level={{ .Values.operator.logLevel }}
          {{- if .Values.operator.image.env }}
          env:
          {{- range .Values.operator.image.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
          {{- end }}
          image: {{ .Values.operator.image.name }}:{{ .Values.operator.image.tag }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          name: {{ .Values.operator.name }}
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var
              name: vardir
            - mountPath: /run
              name: rundir
          {{- if .Values.operator.isDind }}
            - mountPath: /run/containerd
              name: containerdsock
          {{- end }}
      terminationGracePeriodSeconds: 10
{{- end }}
